@@ .. @@
         email = COALESCE((p_form_data->>'email')::text, email),
-        counselling_date = COALESCE((p_form_data->>'selectedDate')::text, counselling_date),
-        counselling_time = COALESCE((p_form_data->>'selectedSlot')::text, counselling_time),
-        counselling_slot_picked = COALESCE((p_form_data->>'selectedDate')::text IS NOT NULL AND (p_form_data->>'selectedSlot')::text IS NOT NULL, counselling_slot_picked),
+        counselling_date = COALESCE((p_form_data->>'counsellingDate')::text, counselling_date),
+        counselling_time = COALESCE((p_form_data->>'counsellingTime')::text, counselling_time),
+        counselling_slot_picked = COALESCE((p_form_data->>'counsellingSlotPicked')::boolean, counselling_slot_picked),
         lead_category = COALESCE((p_form_data->>'lead_category')::text, lead_category),
@@ .. @@
       email,
-      counselling_date,
-      counselling_time,
-      counselling_slot_picked,
+      counselling_date, 
+      counselling_time,
+      counselling_slot_picked,
       lead_category,
@@ .. @@
       (p_form_data->>'email')::text,
-      (p_form_data->>'selectedDate')::text,
-      (p_form_data->>'selectedSlot')::text,
-      (p_form_data->>'selectedDate')::text IS NOT NULL AND (p_form_data->>'selectedSlot')::text IS NOT NULL,
+      (p_form_data->>'counsellingDate')::text,
+      (p_form_data->>'counsellingTime')::text,
+      (p_form_data->>'counsellingSlotPicked')::boolean,
       (p_form_data->>'lead_category')::text,